//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;

    public partial class BENH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENH()
        {
            this.PHIEUKHAMBENHs = new HashSet<PHIEUKHAMBENH>();
        }

        public int id { get; set; }
        public string MaBenh { get; set; }
        public string TenBenh { get; set; }
        public string TrieuChung { get; set; }
        public int idMaLoaiBenh { get; set; }
        public int idMaThuocDacTri { get; set; }

        public virtual LOAIBENH LOAIBENH { get; set; }
        public virtual THUOC THUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKHAMBENH> PHIEUKHAMBENHs { get; set; }
    }
}