//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;

    public partial class CHITIETBCSUDUNGTHUOC
    {
        public int idMaBCSuDungThuoc { get; set; }
        public int idMaThuoc { get; set; }
        public string DonVi { get; set; }
        public int SoLuong { get; set; }
        public int SoLanDung { get; set; }

        public virtual BC_SUDUNGTHUOC BC_SUDUNGTHUOC { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}