//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;

    public partial class PHIEUKHAMBENH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAMBENH()
        {
            this.CT_PHIEUKHAMBENH = new HashSet<CT_PHIEUKHAMBENH>();
            this.HOADONs = new HashSet<HOADON>();
        }

        public int SoPhieuKhamBenh { get; set; }
        public System.DateTime NgayKham { get; set; }
        public int idMaBenhNhan { get; set; }
        public int MaBenh { get; set; }
        public string TrieuChung { get; set; }

        public int TongTien { get; set; }
        public int TrangThai { get; set; }

        public virtual BENH BENH { get; set; }
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}