//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPMTEntities : DbContext
    {
        public QLPMTEntities()
            : base("name=QLPMTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_DOANHTHU> BC_DOANHTHU { get; set; }
        public virtual DbSet<BC_SUDUNGTHUOC> BC_SUDUNGTHUOC { get; set; }
        public virtual DbSet<BENH> BENHs { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CACHDUNG> CACHDUNGs { get; set; }
        public virtual DbSet<CHITIETBCDOANHTHU> CHITIETBCDOANHTHUs { get; set; }
        public virtual DbSet<CHITIETBCSUDUNGTHUOC> CHITIETBCSUDUNGTHUOCs { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENH { get; set; }
        public virtual DbSet<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual DbSet<DONVI> DONVIs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<LOAIBENH> LOAIBENHs { get; set; }
        public virtual DbSet<LOAITHUOC> LOAITHUOCs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NHOMNGUOIDUNG> NHOMNGUOIDUNGs { get; set; }
        public virtual DbSet<PHIEUKHAMBENH> PHIEUKHAMBENHs { get; set; }
        public virtual DbSet<PHIEUNHAPTHUOC> PHIEUNHAPTHUOCs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<DANGKY> DANGKies { get; set; }
    }
}
