name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: [4.7.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore NuGet packages
      run: nuget restore QuanLyPhongMachTu.sln

    - name: Build
      run: msbuild /p:Configuration=Release QuanLyPhongMachTu.sln