name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }} # Chạy trên các hệ điều hành khác nhau

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # Cấu hình các hệ điều hành

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.7.2' # Phiên bản .NET Framework

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test